# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-v2-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache-v2

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-v2-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn run test
