name: test

on:
  push:
    paths:
      - 'src'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/test.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run generate
